name: autoglm_scrcpy
description: Scrcpy protocol implementation for AutoGLM.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

resolution: workspace

dependencies:
  autoglm_adb:
    path: ../autoglm_adb
  autoglm_core:
    path: ../autoglm_core
  autoglm_logger:
    path: ../autoglm_logger
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.4
  shelf: ^1.4.2
  shelf_static: ^1.1.3
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/scrcpy-server-v3.3.4
    - assets/web_player/
