name: adb_tools
description: ADB client and binary management tools.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  archive: ^3.6.1
  logger_utils:
    git:
      url: https://github.com/sunbird89629/logger_utils.git
      ref: v0.1.0
  dio: ^5.7.0
  path: ^1.9.0

dev_dependencies:
  mockito: ^5.4.4
  test: any
