name: scrcpy_view_example
description: Example app demonstrating scrcpy_view usage.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.10.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  adb_tools:
    path: ../../packages/adb_tools
  scrcpy_view:
    path: ../
  logger_utils:
    # git:
    #   url: https://github.com/sunbird89629/logger_utils.git
    #   ref: v0.1.0
    path: ../../../logger_utils
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
