name: scrcpy_view_example
description: Example app demonstrating scrcpy_view usage.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  scrcpy_adapters:
    path: ../../packages/scrcpy_adapters
  scrcpy_view:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
